version: '3'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: mysql/mysql-server
        environment:
            MYSQL_DATABASE: 'su_akismet'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_HOST: '%'
        ports:
            - "3306:3306"
        volumes:
            - ./var/data/mysql:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###
