sulu_form:
    mail:
        from: "%env(SULU_ADMIN_EMAIL)%"
        to: "%env(SULU_ADMIN_EMAIL)%"
        sender: "%env(SULU_ADMIN_EMAIL)%"
    media:
        protected: true

    honeypot:
        field: HoneyPot
        strategy: no_save

framework:
    esi: true
    fragments: true
